// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoYdVIHqjRUBKvttomU0t6kVkayQMV35U',
    appId: '1:1038660924416:web:bd288744c3face003a14e5',
    messagingSenderId: '1038660924416',
    projectId: 'maccaveapp',
    authDomain: 'maccaveapp.firebaseapp.com',
    storageBucket: 'maccaveapp.appspot.com',
    measurementId: 'G-6QX2PF3P0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADdkN8zl5lQv-njhTJjCyZpMCm8UweyPY',
    appId: '1:1038660924416:android:087a735d715922633a14e5',
    messagingSenderId: '1038660924416',
    projectId: 'maccaveapp',
    storageBucket: 'maccaveapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ6VWnjrhvqj13UURn5fjjKWAvKYzkKHQ',
    appId: '1:1038660924416:ios:66f19c96bdd40bd33a14e5',
    messagingSenderId: '1038660924416',
    projectId: 'maccaveapp',
    storageBucket: 'maccaveapp.appspot.com',
    iosClientId: '1038660924416-nr6b3evrpglkudb9irufunvrjbe1bemt.apps.googleusercontent.com',
    iosBundleId: 'com.jhcompany.maccave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ6VWnjrhvqj13UURn5fjjKWAvKYzkKHQ',
    appId: '1:1038660924416:ios:66f19c96bdd40bd33a14e5',
    messagingSenderId: '1038660924416',
    projectId: 'maccaveapp',
    storageBucket: 'maccaveapp.appspot.com',
    iosClientId: '1038660924416-nr6b3evrpglkudb9irufunvrjbe1bemt.apps.googleusercontent.com',
    iosBundleId: 'com.jhcompany.maccave',
  );
}
